;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Control Panel]
Pos=0,0
Size=915,1042
Collapsed=0
DockId=0xAFC85805,0
LastUsed=20260922

[Window][Terminal]
Pos=0,0
Size=915,1042
Collapsed=0
DockId=0xAFC85805,1
LastUsed=20260922

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0
LastUsed=20260922

[Docking][Data]
DockSpace ID=0xAFC85805 Window=0x079D3A04 Pos=0,0 Size=915,1042 CentralNode=1 Selected=0xD33228A6


;;;<<<Layout_655921752_Default>>>;;;
[Visibility]
1057920958_Terminal=true
972997451_Control_Panel=true

;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker

;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{"MainDockSpace":2949142533}}
