# From polybar/colors.ini

theme[main_bg]="#1D2C22"
theme[main_fg]="#BECEBB"
theme[title]="#65C0A6"
theme[hi_fg]="#65C0A6"
theme[selected_bg]="#3D6556"
theme[selected_fg]="#BECEBB"
theme[inactive_fg]="#5B6C64"
theme[graph_text]="#65C0A6"
theme[meter_bg]="#26382D"
theme[proc_misc]="#65C0A6"

theme[cpu_box]="#65C0A6"
theme[mem_box]="#65C0A6"
theme[net_box]="#65C0A6"
theme[proc_box]="#65C0A6"
theme[div_line]="#3D6556"

theme[temp_start]="#9ece6a"
theme[temp_mid]="#65C0A6"
theme[temp_end]="#f7768e"

theme[cpu_start]="#9ece6a"
theme[cpu_mid]="#65C0A6"
theme[cpu_end]="#f7768e"

theme[free_start]="#f7768e"
theme[free_mid]="#65C0A6"
theme[free_end]="#9ece6a"

theme[cached_start]="#9ece6a"
theme[cached_mid]="#65C0A6"
theme[cached_end]="#f7768e"

theme[available_start]="#f7768e"
theme[available_mid]="#65C0A6"
theme[available_end]="#9ece6a"

theme[used_start]="#9ece6a"
theme[used_mid]="#65C0A6"
theme[used_end]="#f7768e"

theme[download_start]="#9ece6a"
theme[download_mid]="#65C0A6"
theme[download_end]="#f7768e"

theme[upload_start]="#9ece6a"
theme[upload_mid]="#65C0A6"
theme[upload_end]="#f7768e"

theme[process_start]="#5B6C64"
theme[process_mid]="#BECEBB"
theme[process_end]="#65C0A6"
