backend = "glx";
vsync = true;
unredir-if-possible = false;
xrender-sync-fence = false;
use-damage = false;
fading = false;
shadow = false;
dithered-present = false;
blur-background-fixed = true;

blur: {
  method = "dual_kawase";
  strength = 8;
};

rules: ({
  match = "class_g = 'Rofi' && (name = 'wallpaper' || name = 'powermenu')";
  blur-background = true;
})
