backend = "glx";
vsync = true;
unredir-if-possible = false;
xrender-sync-fence = false;
use-damage = false;
fading = false;
shadow = false;
dithered-present = false;
blur-background-fixed = true;

blur: {
  method = "dual_kawase";
  strength = 8;
};

rules: (
# picom-panel-opacity
# enabled = false;
# amount = 95;
# /picom-panel-opacity
  { blur-background = false; },
  {
    match = "class_g = 'Polybar' || class_g = 'Dunst' || (class_g = 'Rofi' && (name = 'rofi - wallpaper' || name = 'rofi - powermenu'))";
    corner-radius = 0;
  },
  {
    match = "class_g = 'Rofi' && (name = 'rofi - wallpaper' || name = 'rofi - powermenu')";
    blur-background = true;
  }
)
corner-radius = 16;
shadow-color = "#000000";
blur-background = false;
fade-in-step = 0.46;
fade-out-step = 0.46;
