# polybar
bg0 = #00000000
bg = #161117
fg = #DBD6DD
primary = #D9ADE8
disabled = #757176

# lockscreen
lockscreen_bg= #161117
lockscreen_fg= #D9ADE8
lockscreen_ring= #DBD6DD
lockscreen_date= #D9ADE8
lockscreen_verify= #9ece6a
lockscreen_wrong= #f7768e

# control panel
control_panel_bg= #161117
control_panel_accent= #D9ADE8
control_panel_text= #DBD6DD
control_panel_button_text= #DBD6DD
control_panel_button= #1B191C
control_panel_button_hovered= #4B3E50
control_panel_button_active= #4B3E50
control_panel_frame= #2C2633
control_panel_frame_hovered= #3A3344
control_panel_frame_active= #4A3D50
control_panel_tab= #1B191C
control_panel_tab_hovered= #4A3D50
control_panel_tab_selected= #4A3D50
control_panel_popup= #1B191C
control_panel_popup_border= #4A3D50
control_panel_header= #4A3D50
control_panel_header_hovered= #4A3D50
control_panel_header_active= #4A3D50