#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width        1
bspc config window_gap          5

bspc config top_padding    0
bspc config bottom_padding 0
bspc config left_padding   -5
bspc config right_padding  -5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

setxkbmap -layout "us,ru,ua" -option "grp:alt_shift_toggle"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# notification
pgrep -x dunst >/dev/null || dunst &


# screen shot
pgrep -x flameshot >/dev/null || flameshot &


# bar
killall -q polybar
polybar down-panel &


# background
feh --bg-fill "$HOME/.config/bspwm/pictures/background.jpg" &
