confirm_os_window_close 0
enable_audio_bell no
visual_bell_duration 0
window_alert_on_bell no
background #1D2C22
foreground #BECEBB
active_border_color #65C0A6
inactive_border_color #65C0A6
font_size 11
allow_remote_control socket-only
