# polybar
bg0 = #00000000
bg = #1D2C22
fg = #BECEBB
primary = #65C0A6
disabled = #5B6C64

# lockscreen
lockscreen_bg= #1D2C22
lockscreen_fg= #BECEBB
lockscreen_ring= #65C0A6
lockscreen_date= #65C0A6
lockscreen_verify= #9ece6a
lockscreen_wrong= #f7768e

# control panel
control_panel_bg= #1D2C22
control_panel_accent= #65C0A6
control_panel_text= #BECEBB
control_panel_button_text= #BECEBB
control_panel_button= #26382D
control_panel_button_hovered= #3D6556
control_panel_button_active= #3D6556
control_panel_frame= #345445
control_panel_frame_hovered= #3E6252
control_panel_frame_active= #4A7562
control_panel_tab= #26382D
control_panel_tab_hovered= #3D6556
control_panel_tab_selected= #3D6556
control_panel_popup= #26382D
control_panel_popup_border= #3D6556
control_panel_header= #3D6556
control_panel_header_hovered= #3D6556
control_panel_header_active= #3D6556