# From polybar/colors.ini

theme[main_bg]="#161117"
theme[main_fg]="#DBD6DD"
theme[title]="#D9ADE8"
theme[hi_fg]="#D9ADE8"
theme[selected_bg]="#4B3E50"
theme[selected_fg]="#DBD6DD"
theme[inactive_fg]="#757176"
theme[graph_text]="#D9ADE8"
theme[meter_bg]="#1B191C"
theme[proc_misc]="#D9ADE8"

theme[cpu_box]="#D9ADE8"
theme[mem_box]="#D9ADE8"
theme[net_box]="#D9ADE8"
theme[proc_box]="#D9ADE8"
theme[div_line]="#4A3D50"

theme[temp_start]="#9ece6a"
theme[temp_mid]="#D9ADE8"
theme[temp_end]="#f7768e"

theme[cpu_start]="#9ece6a"
theme[cpu_mid]="#D9ADE8"
theme[cpu_end]="#f7768e"

theme[free_start]="#f7768e"
theme[free_mid]="#D9ADE8"
theme[free_end]="#9ece6a"

theme[cached_start]="#9ece6a"
theme[cached_mid]="#D9ADE8"
theme[cached_end]="#f7768e"

theme[available_start]="#f7768e"
theme[available_mid]="#D9ADE8"
theme[available_end]="#9ece6a"

theme[used_start]="#9ece6a"
theme[used_mid]="#D9ADE8"
theme[used_end]="#f7768e"

theme[download_start]="#9ece6a"
theme[download_mid]="#D9ADE8"
theme[download_end]="#f7768e"

theme[upload_start]="#9ece6a"
theme[upload_mid]="#D9ADE8"
theme[upload_end]="#f7768e"

theme[process_start]="#757176"
theme[process_mid]="#DBD6DD"
theme[process_end]="#D9ADE8"
