# polybar
bg0 = #00000000
bg = #161117
fg = #DBD6DD
primary = #D9ADE8
disabled = #757176

# lockscreen
lockscreen_bg= #161117
lockscreen_fg= #D9ADE8
lockscreen_ring= #DBD6DD
lockscreen_date= #D9ADE8
lockscreen_verify= #9ece6a
lockscreen_wrong= #f7768e