;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
#;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #00000000
background-alt = #373B41
background-alt-3 = #000000
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/down-panel]
bottom = true
width = 100%

override-redirect = false
wm-restack = bspwm
#wm-restack = bspwm
#height = 24pt
#radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt
#line-size = 5pt

#border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 0

module-margin = 0

#separator = "  "
#separator-foreground = ${colors.background-alt-3}

#font-0 = Liberation Sans;2
#font-1 = JetBrainsMono Nerd Font;2
#font-2 = Symbols Nerd Font;2
font-0 = Liberation Sans:size=12;2
font-1 = JetBrainsMono Nerd Font:size=12;2
font-2 = Symbols Nerd Font Mono:size=12;0
font-3 = MesloLGS NF:style=Regular:size=30;4

modules-left = xworkspaces end1
#modules-left = xworkspaces xwindow
modules-center = end3 memory spacer cpu spacer battery end4 
modules-right = end2 systray spacer pulseaudio spacer xkeyboard spacer wlan spacer date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/systray]
type = internal/tray

format-background = ${colors.background-alt-3}
tray-background = ${colors.background-alt-3}

#format-margin = 8pt
tray-spacing = 5pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt-3}
#label-active-underline= ${colors.primary}
label-active-padding = r

label-occupied = %name%
label-occupied-padding = 2
label-occupied-background = ${colors.background-alt-3}

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-upgent-background = ${colors.background-alt-3}
label-urgent-padding = 2

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-background = ${colors.background-alt-3}
label-empty-padding = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted =     %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "   "
format-volume-prefix-foreground = ${colors.primary}
format-volume-prefix-background = ${colors.background-alt-3}
format-volume = <label-volume>

label-volume = %percentage%%
label-volume-background = ${colors.background-alt-3}

label-muted = " "
label-muted-foreground = ${colors.disabled}
label-muted-background = ${colors.background-alt-3}

[module/xkeyboard]
type = internal/xkeyboard

blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}
label-layout-background = ${colors.background-alt-3}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2

format-background = ${colors.background-alt-3}

format-prefix = "ram  "
format-prefix-font = 1
format-prefix-foreground = ${colors.primary}

label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "cpu  "
format-background = ${colors.background-alt-3}
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 1

format-connected = <label-connected>
format-connected-background = ${colors.background-alt-3}

format-disconnected = <label-disconnected>
format-disconnected-background = ${colors.background-alt-3}

label-connected = 󰇚 %downspeed% 󰕒 %upspeed%
label-disconnected = disconnected

[module/wlan]
inherit = network-base
interface-type = wireless

[module/eth]
inherit = network-base
interface-type = wired

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

format-background = ${colors.background-alt-3}

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/battery]
[module/battery]
type = internal/battery
battery = BAT0
adapter = AC

format-charging-background = ${colors.background-alt-3}
format-discharging-background = ${colors.background-alt-3}
format-full-background = ${colors.background-alt-3}

format-charging-prefix = "bat+   "
format-charging-prefix-foreground = ${colors.primary}

format-discharging-prefix = "bat   "
format-discharging-prefix-foreground = ${colors.primary}

format-full-prefix = "bat   "
format-full-prefix-foreground = ${colors.primary}

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%

[module/spacer]
type = custom/text

label = "   "
label-background = ${colors.background-alt-3}

[module/end1]
type = custom/text

label = "◣"
label-foreground = ${colors.background-alt-3}
label-font = 4


[module/end2]
type = custom/text

label = "◢"
label-foreground = ${colors.background-alt-3}
label-font = 4

[module/end3]
type = custom/text

label = "◖%{O-6px}"
label-foreground = ${colors.background-alt-3}
label-font = 4

[module/end4]
type = custom/text

label = "%{O-6px}◗"
label-foreground = ${colors.background-alt-3}
label-font = 4

; vim:ft=dosini
